---
version: '2'

services:
  nameserver:
    container_name: nameserver
    hostname: localhost
    image: ventz/bind:9.16.6-r0
    ports:
      - 127.0.0.1:54:53/tcp
      - 127.0.0.1:54:53/udp
    volumes:
      - ./keys.conf:/etc/bind/keys.conf
      - ./named.conf:/etc/bind/named.conf.local
      - ./teamvinted.com.zone:/var/cache/bind/teamvinted.com.zone
      - ./123.123.123.in-addr.arpa.zone:/var/cache/bind/123.123.123.in-addr.arpa.zone

